# Generated by Django 4.0.4 on 2022-12-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchName',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomName',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='timePeriod',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
